In [1]:
import pandas_ta as ta
import pandas as pd

In [8]:
df = pd.DataFrame()
df = df.ta.ticker("AAPL").tz_localize(None)

In [16]:
rsi = df.ta.rsi(append=True)
macd = df.ta.macd(append=True)
df.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits,RSI_14,MACD_12_26_9,MACDh_12_26_9,MACDs_12_26_9
Date,,,,,,,,,,,
2023-02-01,143.970001,146.610001,141.320007,145.429993,77663600,0.0,0.0,64.154874,2.542378,1.328175,1.214203
2023-02-02,148.899994,151.179993,148.169998,150.820007,118339000,0.0,0.0,70.782147,3.113906,1.519762,1.594144
2023-02-03,148.029999,157.380005,147.830002,154.500000,154279900,0.0,0.0,74.278695,3.819759,1.780492,2.039267
2023-02-06,152.570007,153.100006,150.779999,151.729996,69858300,0.0,0.0,67.710234,4.108278,1.655209,2.453069
2023-02-07,150.639999,155.229996,150.639999,154.649994,83206400,0.0,0.0,70.656045,4.520442,1.653899,2.866544